2018-12-23 17:48:24,213 ERROR: Exception on /rentpage [GET] [in c:\mjp\micro\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\mjp\micro\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\mjp\micro\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\MJP\micro\app\routes.py", line 213, in rentpage
    return render_template('rentpage.html', data=rentdet)
  File "c:\mjp\micro\env\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\mjp\micro\env\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\mjp\micro\env\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\mjp\micro\env\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\mjp\micro\env\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\MJP\micro\app\templates\rentpage.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\MJP\micro\app\templates\base.html", line 47, in top-level template code
    {% block content %}
  File "C:\MJP\micro\app\templates\rentpage.html", line 8, in block "content"
    <input type="text" class="form-control" id="rentcode" name="rentcode" value="{{ rent.rentcode }}">
  File "c:\mjp\micro\env\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'rent' is undefined
2018-12-23 17:50:51,942 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 17:51:00,020 ERROR: Exception on /rentpage [GET] [in c:\mjp\micro\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\mjp\micro\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\mjp\micro\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\MJP\micro\app\routes.py", line 213, in rentpage
    return render_template('rentpage.html', rents=rentdet)
  File "c:\mjp\micro\env\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\mjp\micro\env\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\mjp\micro\env\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\mjp\micro\env\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\mjp\micro\env\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\MJP\micro\app\templates\rentpage.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\MJP\micro\app\templates\base.html", line 47, in top-level template code
    {% block content %}
  File "C:\MJP\micro\app\templates\rentpage.html", line 8, in block "content"
    <input type="text" class="form-control" id="rentcode" name="rentcode" value="{{ rent.rentcode }}">
  File "c:\mjp\micro\env\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'rent' is undefined
2018-12-23 18:24:18,179 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 18:24:28,191 ERROR: Exception on /rentpage [GET] [in c:\mjp\micro\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\mjp\micro\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\mjp\micro\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\MJP\micro\app\routes.py", line 208, in rentpage
    Rent.source, Rent.deedtype, Rent.status, Rent.salegrade, Rent.price, Rent.note, \
AttributeError: type object 'Rent' has no attribute 'salegrade'
2018-12-23 19:59:53,599 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:03:47,734 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:04:16,720 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:04:21,301 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:17:02,769 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:23:47,649 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:23:53,803 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:31:43,870 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:32:49,746 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:32:59,444 ERROR: Exception on /editrent/1481 [GET] [in c:\mjp\micro\env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\mjp\micro\env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\mjp\micro\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\mjp\micro\env\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\MJP\micro\app\routes.py", line 122, in editrent
    rentdet = Property.query.join(Rent).join(Landlord).outerjoin(Agent).join(typemailto).with_entities(Rent.id, Rent.rentcode, \
NameError: name 'typemailto' is not defined
2018-12-23 20:37:34,294 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:38:01,603 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:38:14,849 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:39:36,608 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:43:51,381 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:43:58,135 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:44:03,326 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-23 20:44:26,448 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-24 19:06:26,054 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
2018-12-24 19:21:35,865 INFO: MicroJinn startup [in C:\MJP\micro\app\__init__.py:47]
